### ISSUE TITLE
عدم ارسال بکاپ به تلگرام

### ISSUE THREAD

**Issue by NIKA5050** [masoudgb/Backupchi#1]
با سلام بنده طبق متد جلو رفتم و توکن تلگرام میخواست که دادم جلوتر چت ایدی میخواست که نمیدونم بنده هم ایدی تلگرام بهش دادم یبار و یک بارم ایدی باتی که ساختم دادم با پیشوند @ ولی چیزی ارسال نکرد داخل تلگرام.. پنل چینی و سنایی هم نصب کردم بازم اتفاقی نیفتاد و تنظیماتم روی 1 دقیقه گذاشتم کجارو اشتباه رفتم ؟

**Comment by masoudgb** [comment]
درود وقت بخیر آیدی عددی خودتون که بات رو ایجاد کردید رو بدید 
به این ربات پیام بدید آیدی عددی رو دریافت کنید
http://t.me/get_id_bot

**Comment by NIKA5050** [comment]
> درود وقت بخیر آیدی عددی خودتون که بات رو ایجاد کردید رو بدید به این ربات پیام بدید آیدی عددی رو دریافت کنید http://t.me/get_id_bot

با تشکر درست شد

**Comment by masoudgb** [comment]
🙏🌹
